"""Add Phase 2 models: TinBao, VuAn, BiCan, LichSuChuyenDoi, TamGiam

Revision ID: 9127ec7ea299
Revises: d99b3753c5cf
Create Date: 2025-11-20 13:10:24.076814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9127ec7ea299'
down_revision = 'd99b3753c5cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create vu_an first (without FK to tin_bao initially)
    op.create_table('vu_an',
    sa.Column('stt', sa.Integer(), nullable=False),
    sa.Column('tin_bao_id', sa.String(length=36), nullable=True),
    sa.Column('dieu_luat', sa.String(length=255), nullable=False),
    sa.Column('toi_danh', sa.String(length=255), nullable=False),
    sa.Column('ngay_xay_ra', sa.Date(), nullable=False),
    sa.Column('noi_xay_ra', sa.Text(), nullable=False),
    sa.Column('thong_tin_vu_an', sa.Text(), nullable=False),
    sa.Column('so_qd_phan_cong_ptt', sa.String(length=100), nullable=True),
    sa.Column('so_qd_phan_cong_dtv', sa.String(length=100), nullable=True),
    sa.Column('ngay_phan_cong', sa.Date(), nullable=True),
    sa.Column('so_khoi_to_vu_an', sa.String(length=100), nullable=True),
    sa.Column('ngay_khoi_to_vu_an', sa.Date(), nullable=True),
    sa.Column('tong_so_bi_can', sa.Integer(), nullable=True),
    sa.Column('thong_tin_bi_can', sa.Text(), nullable=True),
    sa.Column('bien_phap_ngan_chan', sa.String(length=100), nullable=True),
    sa.Column('so_khoi_to_bi_can', sa.String(length=100), nullable=True),
    sa.Column('ngay_khoi_to_bi_can', sa.Date(), nullable=True),
    sa.Column('dang_vien', sa.String(length=100), nullable=True),
    sa.Column('ket_qua_giai_quyet', sa.String(length=100), nullable=True),
    sa.Column('bi_can_giai_quyet', sa.Text(), nullable=True),
    sa.Column('dieu_tra_vien', sa.String(length=100), nullable=False),
    sa.Column('can_bo_quan_ly_ho_so', sa.String(length=100), nullable=True),
    sa.Column('don_vi', sa.String(length=100), nullable=True),
    sa.Column('kiem_sat_vien', sa.String(length=100), nullable=True),
    sa.Column('ngay_het_han', sa.Date(), nullable=True),
    sa.Column('tinh_trang_ho_so', sa.String(length=100), nullable=True),
    sa.Column('ghi_chu', sa.Text(), nullable=True),
    sa.Column('trang_thai', sa.String(length=50), nullable=False),
    sa.Column('ngay_chuyen_tu_tin_bao', sa.Date(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stt')
    )
    # Now create tin_bao with FK to vu_an
    op.create_table('tin_bao',
    sa.Column('stt', sa.Integer(), nullable=False),
    sa.Column('dieu_luat', sa.String(length=255), nullable=False),
    sa.Column('ten_nguon_tin', sa.String(length=255), nullable=True),
    sa.Column('ngay_xay_ra', sa.Date(), nullable=False),
    sa.Column('noi_xay_ra', sa.Text(), nullable=False),
    sa.Column('noi_dung_nguon_tin', sa.Text(), nullable=False),
    sa.Column('so_qd_phan_cong_ptt', sa.String(length=100), nullable=True),
    sa.Column('so_qd_phan_cong_dtv', sa.String(length=100), nullable=True),
    sa.Column('ngay_phan_cong', sa.Date(), nullable=True),
    sa.Column('ket_qua_giai_quyet', sa.String(length=50), nullable=True),
    sa.Column('dia_chi_bi_hai', sa.Text(), nullable=True),
    sa.Column('thong_tin_doi_tuong', sa.Text(), nullable=True),
    sa.Column('cong_an_phu_trach', sa.String(length=100), nullable=True),
    sa.Column('don_vi', sa.String(length=100), nullable=True),
    sa.Column('kiem_sat_vien', sa.String(length=100), nullable=True),
    sa.Column('gia_han', sa.Integer(), nullable=True),
    sa.Column('ngay_het_han', sa.Date(), nullable=True),
    sa.Column('tinh_trang_ho_so', sa.String(length=100), nullable=True),
    sa.Column('ghi_chu', sa.Text(), nullable=True),
    sa.Column('trang_thai', sa.String(length=50), nullable=False),
    sa.Column('vu_an_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['vu_an_id'], ['vu_an.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stt')
    )
    # Now add FK from vu_an to tin_bao
    op.create_foreign_key('fk_vu_an_tin_bao_id', 'vu_an', 'tin_bao', ['tin_bao_id'], ['id'], ondelete='SET NULL')
    op.create_table('bi_can',
    sa.Column('vu_an_id', sa.String(length=36), nullable=False),
    sa.Column('ho_ten', sa.String(length=100), nullable=False),
    sa.Column('nam_sinh', sa.Integer(), nullable=False),
    sa.Column('dia_chi_thuong_tru', sa.Text(), nullable=False),
    sa.Column('so_cmnd', sa.String(length=20), nullable=True),
    sa.Column('nghe_nghiep', sa.String(length=100), nullable=True),
    sa.Column('dang_vien', sa.Boolean(), nullable=True),
    sa.Column('bien_phap_ngan_chan', sa.String(length=100), nullable=True),
    sa.Column('so_khoi_to_bi_can', sa.String(length=100), nullable=True),
    sa.Column('ngay_khoi_to', sa.Date(), nullable=True),
    sa.Column('trang_thai', sa.String(length=50), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['vu_an_id'], ['vu_an.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lich_su_chuyen_doi',
    sa.Column('tin_bao_id', sa.String(length=36), nullable=False),
    sa.Column('vu_an_id', sa.String(length=36), nullable=False),
    sa.Column('ngay_chuyen', sa.DateTime(), nullable=False),
    sa.Column('nguoi_chuyen', sa.String(length=100), nullable=True),
    sa.Column('ly_do', sa.Text(), nullable=True),
    sa.Column('ghi_chu', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['tin_bao_id'], ['tin_bao.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vu_an_id'], ['vu_an.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tam_giam',
    sa.Column('vu_an_id', sa.String(length=36), nullable=False),
    sa.Column('bi_can_id', sa.String(length=36), nullable=False),
    sa.Column('ngay_bat_giam', sa.Date(), nullable=False),
    sa.Column('ngay_het_han_giam', sa.Date(), nullable=False),
    sa.Column('ly_do_tam_giam', sa.Text(), nullable=False),
    sa.Column('trang_thai_giam', sa.String(length=50), nullable=True),
    sa.Column('ghi_chu', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['bi_can_id'], ['bi_can.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vu_an_id'], ['vu_an.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tam_giam')
    op.drop_table('lich_su_chuyen_doi')
    op.drop_table('bi_can')
    op.drop_table('vu_an')
    op.drop_table('tin_bao')
    # ### end Alembic commands ###
